name: 'release'

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - id: version
        name: Determine next version
        uses: conventional-actions/next-version@e48c1275d221bd29e2c08f8856b91695c0a72db1 # v1.1.6
      - name: Create release
        uses: conventional-actions/create-release@50cd05b8ea9f2f3f32bbb822706b01ebf2ccce62 # v1.0.29
        with:
          tag_name: ${{steps.version.outputs.version}}
      - name: Create major release
        uses: conventional-actions/create-release@50cd05b8ea9f2f3f32bbb822706b01ebf2ccce62 # v1.0.29
        with:
          tag_name: ${{steps.version.outputs.version-major}}

permissions:
  contents: write
